package common.connectivity;

import java.io.Serializable;

public enum MessageFromServer implements Serializable {
    IMPORT_ORDER_TABLE_UNSUCCESSFUL,
    LOGIN_FAILED_ALREADY_LOGGED_IN,
    IMPORT_USER_TABLE_SUCCESSFUL,
    IMPORT_ORDER_TABLE_COMPLETE,
    LOGOUT_ERROR_NOT_LOGGED_IN,
    DELETE_USER_UNSUCCESSFUL,
    IMPORT_USER_UNSUCCESSFUL,
    DELETE_USER_SUCCESSFUL,
    ADD_USER_UNSUCCESSFUL,
    UPDATE_UNSUCCESSFUL,
    ADD_USER_SUCCESSFUL,
    UPDATE_SUCCESSFUL,
    LOGOUT_SUCCESSFUL,
    LOGIN_SUCCESSFUL,
    LOGOUT_ERROR,
    USER_EXISTS,
    LOGIN_ERROR,
    UNKNOWN_TASK
}
